@extends('layouts.app')
<!-- ChatGPT helped with layout and styling on this page. -->
@section('content')
<div class="absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80" aria-hidden="true">
    <div class="relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]"
        style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)">
    </div>
</div>
<div class="max-w-4xl mx-auto bg-white rounded-lg shadow p-6">
    <h1 class="text-2xl font-bold mb-4">Select Your Team</h1>

    {{-- Budget Info --}}
    <div class="mb-4 text-gray-700">
        <strong>Budget Remaining:</strong> £<span id="budgetDisplay">100.0</span> / 100
    </div>

    @if ($errors->any())
    <div class="bg-red-100 border-l-4 border-red-500 text-red-700 p-4 mb-6 rounded shadow">
        <h3 class="font-semibold text-lg mb-2">Error:</h3>
        <ul class="list-disc pl-5 space-y-1 text-sm">
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    {{-- Selection Form --}}
    <form method="POST" action="{{ route('team.store.initial') }}">
        @csrf

        @php
        $positions = [
        'GK' => ['label' => 'Goalkeeper', 'count' => 2],
        'DF' => ['label' => 'Defender', 'count' => 5],
        'MF' => ['label' => 'Midfielder', 'count' => 5],
        'FW' => ['label' => 'Forward', 'count' => 3],
        ];
        @endphp

        @foreach($positions as $code => $info)
        <div class="mb-8">
            <h2 class="text-xl font-semibold text-purple-700 mb-4 border-b border-purple-200 pb-1">{{ $info['label'] }}s</h2>
            <div class="space-y-3">
                @for ($i = 1; $i <= $info['count']; $i++)
                    <div class="bg-purple-50 border border-purple-200 rounded-lg px-4 py-2 flex items-center shadow-sm hover:shadow-md transition-all">
                    <span class="font-medium text-gray-700 w-32">Pick {{ $info['label'] }} {{ $i }}</span>
                    <select name="players[]" class="ml-4 flex-1 border border-gray-300 rounded p-2 focus:outline-none focus:ring-2 focus:ring-purple-500 player-select" onchange="updateBudget()">
                        <option value="" disabled selected>Select a {{ $info['label'] }}</option>
                        @foreach($players->where('position', $code) as $player)
                        <option value="{{ $player->id }}" data-price="{{ $player->value }}">
                            {{ $player->name }} ({{ $player->team->name ?? 'No Team' }}) – £{{ number_format($player->value, 1) }}
                        </option>
                        @endforeach
                    </select>
            </div>
            @endfor
        </div>
</div>
@endforeach

<div class="mt-8 flex items-center justify-between">
    <div class="text-lg text-purple-700 font-medium">
        Budget Remaining: £<span id="budgetDisplay">100.0</span> / 100
    </div>
    <button type="submit" class="!bg-purple-600 hover:bg-purple-700 text-white px-6 py-2 rounded-lg shadow">
        Submit Team
    </button>
</div>
</form>
</div>
<div class="absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-30rem)]" aria-hidden="true">
    <div class="relative left-[calc(50%+3rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%+36rem)] sm:w-[72.1875rem]"
        style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)">
    </div>
</div>

{{-- Budget Tracker Script --}}
<!-- This JS was generated by ChatGPT to help me live update the budget spent -->
<script>
    function updateBudget() {
        let total = 0;
        document.querySelectorAll('.player-select').forEach(select => {
            const selected = select.options[select.selectedIndex];
            const price = selected?.dataset?.price;
            if (price) total += parseFloat(price);
        });
        document.getElementById('budgetDisplay').textContent = (100 - total).toFixed(1);
    }
    window.onload = updateBudget;
</script>
@endsection